### PR TITLE
Add vineyardctl for managing vineyard operator and relavant compenents on kubernetes

### PR DESCRIPTION
**Pull request by sighingnow**
What do these changes do?
-------------------------

Preview the changeset, DON'T MERGE!

### CODE REVIEW

**Comment by sighingnow** [comment]
Submit pull request to the dev/kubernetes branch. Don't directly update this PR otherwise we would been in huge conflict.

**Comment by sighingnow** [comment]
> Submit pull request to the dev/kubernetes branch. Don't directly update this PR otherwise we would been in huge conflict.

**Comment by dashanji** [comment]
Okay, I will revert and submit it to the dev/kubernetes branch.

**Comment by sighingnow** [comment]
I just realized we actually implements the same logic/task twice, one in reconciler and another in the cmd package. The former take advantage of `swkckube` and another is using `kubectl`...

**Comment by sighingnow** [comment]
There looks some bugs in documentation formatting:

image

**Comment by dashanji** [comment]
> There looks some bugs in documentation formatting:
> 
> image

I will format the description as the util.Example...

**Pull request merged**
