### PR TITLE
Remove build warnings for graph part.

### PR DESCRIPTION
**Pull request by SighingSnow**
Fix build warnings in graph.

### CODE REVIEW

**Comment by SighingSnow** [comment]
@sighingnow could you help me review this little commit mentioned yesterday.

**Comment by sighingnow** [comment]
Can you try fixes all these warnings mentioned in https://github.com/v6d-io/v6d/issues/1295?

You can `make clean` first then `make` as a double check.

**Comment by SighingSnow** [comment]
Yes, I will give it a double check. I am sorry about that I didn't check the warnings carefully.

**Comment by SighingSnow** [comment]
@sighingnow could you give it another check when you are free. Best wishes for the comming soon holiday.

**Pull request merged**
