### PR TITLE
Implement etcd lifecycle management for vineyardd

### PR DESCRIPTION
**Pull request by dashanji**
What do these changes do?
-------------------------

* Add the etcdctl cmd flag.
* Launch an etcd instance when start a vineyardd instance.
* Remove the related etcd member when a vineyardd instance exit.

Related issue number
--------------------

Fixes https://github.com/v6d-io/v6d/issues/1922

### CODE REVIEW

**Review by sighingnow — COMMENTED** [review]
You would better integrate these etcd member control APIs into etcd-cpp-apiv3 and avoid subprocess calls later.

**Review by sighingnow — COMMENTED** [review]
Please add a test suite to ensure it works.

**Comment by dashanji** [comment]
> Please add a test suite to ensure it works.

Okay.

**Comment by dashanji** [comment]
> Please add a test suite to ensure it works.

Done. 

@sighingnow Could you please take a look at this?

**Pull request merged**
