### PR TITLE
Small code improvement of graph

### PR DESCRIPTION
**Pull request by songqing**
What do these changes do?
-------------------------

Just code lint fix and small hard-code var's fix

Related issue number
--------------------

### CODE REVIEW

**Review by sighingnow — APPROVED** [review]
Thanks for fixing them. You need to format & lint the source code as what we do in CI: https://github.com/v6d-io/v6d/actions/runs/4697904211/jobs/8329528434?pr=1314

Note that clang-format-8 is required: https://github.com/muttleyxd/clang-tools-static-binaries/releases

**Comment by songqing** [comment]
> Thanks for fixing them. You need to format & lint the source code as what we do in CI: https://github.com/v6d-io/v6d/actions/runs/4697904211/jobs/8329528434?pr=1314
> 
> Note that clang-format-8 is required: https://github.com/muttleyxd/clang-tools-static-binaries/releases

A little weird, the code format in old file "arrow_fragment.vineyard-mod" is not  in accordance with clang-format, I'll have a check.

**Comment by sighingnow** [comment]
> A little weird, the code format in old file "arrow_fragment.vineyard-mod" is not in accordance with clang-format, I'll have a check.

Try `make vineyard_clformat`.

See also: https://github.com/v6d-io/v6d/blob/main/CMakeLists.txt#L909-L945

**Comment by songqing** [comment]
> > A little weird, the code format in old file "arrow_fragment.vineyard-mod" is not in accordance with clang-format, I'll have a check.
> 
> Try `make vineyard_clformat`.
> 
> See also: https://github.com/v6d-io/v6d/blob/main/CMakeLists.txt#L909-L945

I have run the command, but it seems after the command, file format is not in accordance with other file, for example, after run the command, "&" is not in the right place
f1

**Comment by sighingnow** [comment]
Can you show me your clang-format version?

```
clang-format --version
```

Vineyard CI uses clang-format-8.

**Comment by songqing** [comment]
> 

clang-format version 8.0.1 (tags/RELEASE_801/final)

**Comment by songqing** [comment]
> Can you show me your clang-format version?
> 
> ```
> clang-format --version
> ```
> 
> Vineyard CI uses clang-format-8.

@sighingnow When I change clang-format's version to 11, it seems the file "arrow_fragment.vineyard-mod"'s format is in accordance with other files

**Comment by sighingnow** [comment]
> When I change clang-format's version to 11, it seems the file "arrow_fragment.vineyard-mod"'s format is in accordance with other files

Upgrade clang-format should be ok as well.

**Pull request merged**
