### PR TITLE
Add the namespace configurations to the podAffinity and delete the legacy '--wait' flag of helm chart

### LINKED ISSUE #1501: The workload can't be scheduled on the vineyard cluster deployed on different namespace
Describe your problem
---------------------

1. Deploy the vineyard deployment as follows.

```bash
$ vineyardctl deploy vineyard-deployment --replicas=1 --create-namespace
```

2. Assume we have the following workload yaml.

```yaml
$ cat workload.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-client
  namespace: vineyard-job
spec:
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: python:3.10
        command: ["python", "-c", "import time; time.sleep(100000)"]
```

3. Then schedule the workload to the vineyard deployment as follows.

```bash
$ kubectl create ns vineyard-job && vineyardctl schedule workload -f workload.yaml | kubectl apply -f -
```

4. The workload pod will always keep pending as no nodes are available.

### PR DESCRIPTION
**Pull request by dashanji**
What do these changes do?
-------------------------

As titled.

Related issue number
--------------------

Fixes #1501

### CODE REVIEW

**Review by sighingnow — APPROVED** [review]

**Review by sighingnow — APPROVED** [review]

**Comment by sighingnow** [comment]
Why the bad case also pass CI?

**Comment by dashanji** [comment]
> Why the bad case also pass CI?

Sorry, I mixed the e2e test name as it didn't run actually.

**Comment by sighingnow** [comment]
What's the difference between these two test cases `schedule-workload` and `scheduling-outside-cluster`?

**Comment by dashanji** [comment]
> What's the difference between these two test cases `schedule-workload` and `scheduling-outside-cluster`?

They are all scheduled outside scheduler plugin. `schedule-workload` is tested for the command `vineyardctl schedule workload` and `scheduling-outside-cluster` is tested for the command `vineyardctl schedule workflow`. Maybe `schedule-workflow` looks better? @sighingnow

**Comment by sighingnow** [comment]
I see. Ok to leave both.

Thanks for making it clear.

**Pull request merged**
