### PR TITLE
Release vineyard-operator in ci

### PR DESCRIPTION
**Pull request by dashanji**
In the pr, we'll release the nightly version of vineyard-operator in every pr and push the release version of vineyard-operator when releasing the vineyardd.

### CODE REVIEW

**Comment by sighingnow** [comment]
Why k8s CI is not triggered by this PR?

Please add the `vineyard-operator.yaml` to the allow list of the k8s CI.

**Comment by dashanji** [comment]
> Why k8s CI is not triggered by this PR?
> 
> Please add the `vineyard-operator.yaml` to the allow list of the k8s CI.

Sorry for that, we don't modify the file in the path `/k8s/*` here. =.=

**Comment by dashanji** [comment]
Done. The vineyard-operator CI will be triggered in every pr, so the version of vineyard-operator image will be the same as the vineyard.

**Comment by sighingnow** [comment]
> Done. The vineyard-operator CI will be triggered in every pr, so the release version of vineyard-operator image will be the same as the vineyard.

I don't mean "in every pr", actually I mean, in PRs where the `.github/workflows/vineyard-operator.yaml` is updated.

**Comment by dashanji** [comment]
oh, I understand your meaning.

**Pull request merged**
