### PR TITLE
Remove the unused vineyardjob CRD and refactor the scheduler plugin codebase

### LINKED ISSUE #911: Remove the unused `VineyardJob` source code and controller in k8s/ directory
Describe your problem
---------------------

It is not used anymore and has been proved as a failure experiment. I will clean up this part for preparation about our next k8s development stage.

Additional context
------------------

Will done before the end of this week.

### PR DESCRIPTION
**Pull request by sighingnow**
What do these changes do?
-------------------------

- The `VineyardJob` won't be used anymore
- The controller for `LocalObjects` and `GlobalObjects` and the scheduler plugin are merged back into a single binary (deployment)

Related issue number
--------------------

Fixes #911

### CODE REVIEW

**Comment by sighingnow** [comment]
Follow-up work on https://github.com/v6d-io/v6d/pull/912

**Review by dashanji — APPROVED** [review]
What do you think about separating the scheduler and the operator into two workloads?

**Comment by sighingnow** [comment]
> 

We don't need to do something about the created `LocalObject` and `GlobalObject` resources in the controller (you can see that the corresponding `Reconciler` function is just a noop).

The CRDs are just designed to make the data in vineyardd observable from the scheduler plugin.

**Comment by dashanji** [comment]
Make sense.

**Pull request merged**
