### PR TITLE
Lightweight metadata service backend for vineyard

### LINKED ISSUE #725: Support lightweight metadata service backend (e.g., redis) in Vineyard
Describe your problem
---------------------

Vineyard is a distributed system that manages data pieces placed across many machines. Vineyard depends on a metadata service to synchronize information between nodes about the distribution of data pieces and provides a view of global objects for clients. Vineyard currently implements the metadata service using etcd as the backend, archieve high availability and reliable consistent. However there are cases where the strong reliability of metadata is not a necessity and its is annoying to deploy a etcd cluster with multiple replication. and kv store like redis are commonly used for such scenario.

In this task the candidate is responsible for implementing more options for the backend services like redis based on current well-design interfaces. The operation on metadata involves get, put, list, delete, as well as setup a watch stream that can subscribe the update from other nodes and apply the changes in current node in a correct order.

Subtasks
---------

+ [ ] A wramup task to get familiar with the codebase of metadata service
   - [ ] #715
+ [ ] Implementing the support of redis and kine as key-value store backend in the metadata service
   - [ ] #701
   - [ ] #708

Additional context
------------------

This issue is part of our [OSPP 2022](https://summer-ospp.ac.cn/#/org/orgdetail/bb1d0787-db22-4203-b15d-a1f1bf12548b/)

### PR DESCRIPTION
**Pull request by shihao-thx**
What do these changes do?
-------------------------
add redis metadata service.

Related issue number
--------------------

Fixes #725

### CODE REVIEW

**Comment by sighingnow** [comment]
I suggest adding some description about the key-value schema in your `redis_metadata_service.h`, including but not limited to

- which key is used to represent the latest revision
- which key or keyspace is used to establish the watch stream
- which key is used for lock
- how txn is implementated (update the watch queue and k-v pairs in the same txn)
- etc.

**Comment by shihao-thx** [comment]
What you suggested is like the below doing?
```c++
// redis_revision is used to represent the latest revision
redis_->incr("redis_revision").get();

// opslist is used to represent the operations of every commitUpdates
self->redis_->command<long long>(  
              "RPUSH", "opslist", op_prefix);

// operations is used to establish the watch stream
this->watcher_->subscribe("operations");
```
etc.

Regards

**Comment by shihao-thx** [comment]
B.T.W. Should I do something about the problem in my last pr?

**Comment by sighingnow** [comment]
> What you suggested is like the below doing?

I think adding the comments about those keys and queues at the same comment block at somewhere would be more clear.

> B.T.W. Should I do something about the problem in my last pr?

I suggest you first `git revert` the problematic commit ( https://github.com/v6d-io/v6d/pull/902/commits/2e0a5bd00496defbd653fcaa04ffeb69e9a09eab ) and then apply (re-add & commit) necessary changes, then push again.

**Comment by shihao-thx** [comment]
got it.

**Comment by shihao-thx** [comment]
Hi, @sighingnow. I found Vineyard CI gave the error message: `RuntimeError: Unable to find program redis-server` Does it mean the redis-server is not installed?

Regards

**Review by sighingnow — APPROVED** [review]
LGTM.

**Comment by sighingnow** [comment]
Merged to main.

Thanks @shihao-thx for your effort!

**Pull request merged**
