### PR TITLE
Introduce golang lint

### PR DESCRIPTION
**Pull request by dashanji**
What do these changes do?
-------------------------

* Introduce golang lint.
* ~~Update the copyright timeline.~~
* Clean the golang code.

### CODE REVIEW

**Comment by sighingnow** [comment]
I suggest splitting different topics (add golang lint and update the copyright header) into different PRs.

**Comment by dashanji** [comment]
Got it, I will do it later.

**Review by sighingnow — APPROVED** [review]
You could just ignore the source code under `go/` directory. Its a golang SDK implementation for vineyard client and is not in use currently.

**Comment by dashanji** [comment]
Copy that.

**Pull request merged**
