### PR TITLE
Fuse dev work in progress

### PR DESCRIPTION
**Pull request by liusitan**
this fuse file system can read the pyarrow array, and pyarrow table from the vineyard system.  
For more, please refer to the readme in the module/fuse.

[Revert "rename fuse.h"](https://github.com/v6d-io/v6d/commit/2b12875c1f0756ac530da9e3174a6adbe93d87b6) 
commit is a little bit confusing, but mostly it just cleaned the repo.

### CODE REVIEW

**Comment by sighingnow** [comment]
Hi @liusitan,

Could you please consolidate your commits and rebase to current main branch?

Thanks!

**Comment by liusitan** [comment]
sure

**Comment by sighingnow** [comment]
Seems that there's still a lot conflicts.

**Comment by sighingnow** [comment]
Closing as in favour of #889.

**Pull request closed without merging**
