### PR TITLE
use upx to prune vineyardctl binary size

### LINKED ISSUE #1268: Reduce/optimize the binary size of current vineyardctl
Describe your problem
---------------------

Current vineyardctl is about 100M before strip and 70M even after strip, that is not very friendly to distribute the binary.

Not at high priority, and should be done after we finish the refactor of vineyardctl. The optimization could be done by analyze the dependency graph and prune not needed ones.

Additional context
------------------

- [vineyardctl](https://github.com/v6d-io/v6d/tree/main/k8s/cmd)
- [vineyard operator doc](https://v6d.io/notes/cloud-native/vineyard-operator.html)

### PR DESCRIPTION
**Pull request by zhuyi1159**
What do these changes do?
-------------------------

as titled

Related issue number
--------------------

Fixes #1268

### CODE REVIEW

**Comment by zhuyi1159** [comment]
By using upx to compress the generated binary files, the vineyardctl binary files can be compressed to 22MB.

When embedding vineyard into a pypi package, compression is performed by default. However, before using upx, the size of the vineyardctl binary file was 54.84MB. Perhaps using upx can further reduce the size of the vineyardctl binary file.

**Comment by dashanji** [comment]
> By using upx to compress the generated binary files, the vineyardctl binary files can be compressed to 22MB.
> 
> When embedding vineyard into a pypi package, compression is performed by default. However, the size of the vineyardctl binary file was still 54.84MB before using upx, . Perhaps using upx can further reduce the size of the vineyardctl binary file.

LGTM, thanks.

**Review by dashanji — APPROVED** [review]

**Comment by sighingnow** [comment]
Have you folks tested this pull request on

- arm64 (aarch64) linux
- arm64 (m1) macos

?

**Comment by zhuyi1159** [comment]
Not tested, cause I don't have a corresponding machine.
I have only tested on Ubuntu on the x86_64 platform.

**Comment by sighingnow** [comment]
Try https://www.stereolabs.com/docs/docker/building-arm-container-on-x86/

**Comment by dashanji** [comment]
@zhuyi1159  I have tested in the machine (arm64 (m1) macos), can't work:

```bash
$ env CGO_ENABLED=0 GOARCH=arm64 go build -a -o vineyardctl cmd/main.go && upx -9 vineyardctl && ./vineyardctl       
[1]    6128 killed     ./vineyardctl
```

```bash
$ env CGO_ENABLED=0 GOARCH=arm64 go build -a -o vineyardctl cmd/main.go && ./vineyardctl
vineyardctl is the command-line tool for working with the
Vineyard Operator. It supports creating, deleting and checking
status of Vineyard Operator. It also supports managing the
vineyard relevant components such as vineyardd and pluggable
drivers.

Usage:
  vineyardctl [command]

Available Commands:
  create      Create a vineyard jobs on kubernetes
  delete      Delete the vineyard components from kubernetes
  deploy      Deploy the vineyard components on kubernetes
  get         Get vineyard object, metadata, blob or cluster-info
  help        Help about any command
  inject      Inject the vineyard sidecar container into a workload
  ls          List vineyard objects, metadatas or blobs
  manager     Start the manager of vineyard operator
  schedule    Schedule a workload or a workflow to existing vineyard cluster.

Flags:
      --create-namespace    create the namespace if it does not exist, default false
  -j, --dump-usage          Dump usage in JSON
  -g, --gen-doc             Generate reference docs, e.g., "./cmd/README.md"
  -h, --help                help for vineyardctl
      --kubeconfig string   kubeconfig path for the kubernetes cluster (default "/Users/caoye/.kube/config")
  -n, --namespace string    the namespace for operation (default "vineyard-system")
      --verbose             print verbose log, default false
  -v, --version             version for vineyardctl
      --wait                wait for the kubernetes resource to be ready, default true (default true)

Use "vineyardctl [command] --help" for more information about a command.
```

/cc @sighingnow

**Comment by dashanji** [comment]
Worked on the Arm Linux machine.

**Pull request merged**
