### PR TITLE
Fix graph's incremental update

### PR DESCRIPTION
**Pull request by songqing**
What do these changes do?
-------------------------
Small fixes of graph's incremental update

### CODE REVIEW

**Comment by sighingnow** [comment]
Thank a lot @songqing. Its really nice to see people from the community are interested in our ongoing development. Thanks!

@siyuan0322 Could you please take a look? as you are working on debugging the incremental fragment builder as well.

**Comment by SighingSnow** [comment]
> /cc @SighingSnow as well.

Yes, I will check it.

**Comment by SighingSnow** [comment]
> /cc @SighingSnow as well.

Yes, I will check it.

**Review by siyuan0322 — APPROVED** [review]
@songqing Fantastic work!

**Pull request merged**
