### PR TITLE
Add the mount vineyard socket dockerfile for fluid integration

### PR DESCRIPTION
**Pull request by dashanji**
What do these changes do?
-------------------------

Add the mount vineyard socket dockerfile and we need to push it to our official docker hub when merged.

Related issue number
--------------------

Fixes part of #1596

### CODE REVIEW

**Comment by sighingnow** [comment]
Seems this artifacts should be part of vineyard fluid runtime?

**Comment by dashanji** [comment]
> Seems this artifacts should be part of vineyard fluid runtime?

I think it should be a part of vineyard just as `vineyard fuse`.

**Comment by sighingnow** [comment]
It can only be used in the context of fluid ....

**Comment by sighingnow** [comment]
Rename the dir and docker image name to `vineyard-fluid-mount`.

**Review by sighingnow — APPROVED** [review]

**Pull request merged**
