### PR TITLE
Website: Create new landing page

### PR DESCRIPTION
**Pull request by thisisobate**
What do these changes do?
-------------------------

Related issue number
--------------------

Fixes #issue number

### CODE REVIEW

**Comment by sighingnow** [comment]
@thisisobate  Thanks a lot! Looking forward to the final version.

**Comment by thisisobate** [comment]
@sighingnow I noticed the netlify preview step did not run on GH actions.
Have any idea what might be preventing the preview link from showing on this PR?

**Comment by sighingnow** [comment]
> @sighingnow I noticed the netlify preview step did not run on GH actions. Have any idea what might be preventing the preview link from showing on this PR?

Hi @thisisobate,

I have fixed the netlify preview in #1453. Could you please try reopen a new pull request or push something to this pull request to trigger the preview deploy?

Thanks!

**Comment by thisisobate** [comment]
@sighingnow Netlify still breaks.
Can you help take a look?

**Comment by sighingnow** [comment]
@thisisobate Could you please rebase this pull request against the current main branch?

**Comment by sighingnow** [comment]
Hi @thisisobate, could we have a hyperref link like "Get started" or "Learn more" inside the "Use Cases" and "Features" blocks? Just like

image

or 

image

**Comment by thisisobate** [comment]
@sighingnow pushed an update now.
Feel free to take a look

**Comment by sighingnow** [comment]
Hi @thisisobate,

The current implementation looks pretty good. Thanks for your hard work!

I have pushed a commit to this pull request which adjust width of some containers to fit different size of screens and adjust the content of use cases a bit.

**Comment by thisisobate** [comment]
Awesome! 
Thanks alot! @sighingnow

**Comment by sighingnow** [comment]
Hi @thisisobate,

I'm going to get this pull request merged. Do you have any further improvement to be committed to this pr?

Thanks again for your effort and the help from CNCF service deck!

**Comment by thisisobate** [comment]
Oh no…please feel free to go ahead with the merge.
Glad we were able to help!

**Comment by sighingnow** [comment]
> Oh no…please feel free to go ahead with the merge. Glad we were able to help!
> […](#)

Merged. Thanks!

**Pull request merged**
